### ISSUE TITLE
Invalid provider configuration: Empty configuration block seen in generated main.tf.json

### ISSUE THREAD

**Issue by jesusfbn** [ankasoftco/provider-nsxt#2]
Currently in the exploratory phase of using this Crossplane provider to work with VMware NSX.

**What happened?**

I attempted to create a [DHCP Server configurations](https://marketplace.upbound.io/providers/ankasoftco/provider-nsxt/v0.1.0/resources/dhcp.crossplane.io/PolicyDhcpServer/v1alpha1) with Crossplane and I am seeing this error
```
Message:  observe failed: cannot run refresh: refresh failed: username must be provided:
Invalid provider configuration: Provider "registry.terraform.io/vmware/nsxt" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider documentation.
```

**How can we reproduce it?**
In the projects' repository, I followed along with the files found in the example directory. 

1. Install the NSXT Provider
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-nsxt
spec:
  package: ankasoftco/provider-nsxt:v0.1.0
```

2. Create a kubernetes secret
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: example-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "username": "admin",
      "password": "t0ps3cr3t11"
    }
```

3. Create a provider config
```yaml
apiVersion: nsxt.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: example-creds
      namespace: crossplane-system
      key: credentials
```
The only change I made was a change to the value for `apiVersion` from `nsxt.upbound.io/v1beta1` to `nsxt.crossplane.io/v1beta1`

4. Create a managed resource
```yaml
apiVersion: dhcp.crossplane.io/v1alpha1
kind: PolicyDhcpServer
metadata:
  name: nsx-dhcp-server
spec:
  forProvider:
    displayName: "tier_dhcp"
    description: "DHCP server servicing all 3 Segments"
    serverAddresses: 
      - "12.12.99.2/24"
```

Here is the generated `main.tf.json` I see in the nsxt pod
```json
{
    "provider": {
        "nsxt": null
    },
    "resource": {
        "nsxt_policy_dhcp_server": {
            "nsx-dhcp-server": {
                "description": "DHCP server servicing all 3 Segments",
                "display_name": "tier_dhcp",
                "lifecycle": {
                    "prevent_destroy": true
                },
                "server_addresses": [
                    "12.12.99.2/24"
                ]
            }
        }
    },
    "terraform": {
        "required_providers": {
            "nsxt": {
                "source": "vmware/nsxt",
                "version": "3.3.2"
            }
        }
    }
}
```

Am I missing something in how the credentials should be formatted? Any help would be greatly appreciated. Thanks
